const axios = require('axios');

const TOKEN = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJNYXBDbGFpbXMiOnsiYXVkIjoiaHR0cDovLzIwLjI0NC41Ni4xNDQvZXZhbHVhdGlvbi1zZXJ2aWNlIiwiZW1haWwiOiJjYi5zYy51NGN5czIzMDE2QGNiLnN0dWRlbnRzLmFtcml0YS5lZHUiLCJleHAiOjE3NzgwNTkzMTcsImlhdCI6MTc3ODA1ODQxNywiaXNzIjoiQWZmb3JkIE1lZGljYWwgVGVjaG5vbG9naWVzIFByaXZhdGUgTGltaXRlZCIsImp0aSI6IjE5OWNkMzM4LTI1MmUtNDAxMy1hMTE3LTFiZTMwZWU2M2I0NiIsImxvY2FsZSI6ImVuLUlOIiwibmFtZSI6ImhlbWEgbSIsInN1YiI6Ijg5M2JiY2IxLWYzODAtNDdkYS1hY2YwLTIyN2RlYWUzOTkzZSJ9LCJlbWFpbCI6ImNiLnNjLnU0Y3lzMjMwMTZAY2Iuc3R1ZGVudHMuYW1yaXRhLmVkdSIsIm5hbWUiOiJoZW1hIG0iLCJyb2xsTm8iOiJjYi5zYy51NGN5czIzMDE2IiwiYWNjZXNzQ29kZSI6IlBUQk1tUSIsImNsaWVudElEIjoiODkzYmJjYjEtZjM4MC00N2RhLWFjZjAtMjI3ZGVhZTM5OTNlIiwiY2xpZW50U2VjcmV0IjoiU0Z1c1dBZkNlZ3VobXFEQyJ9.f5CjUTmm9i2MUDNVlwq49Gcv8qmYrCOq7Xf7nmsoQxg";
axios.get('http://20.207.122.201/evaluation-service/notifications', {
  headers: { Authorization: 'Bearer ' + TOKEN }
})
.then(r => console.log(JSON.stringify(r.data, null, 2)))
.catch(e => console.log('ERROR:', e.response ? JSON.stringify(e.response.data) : e.message));